# Generated by Django 4.2.7 on 2023-11-06 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_word_synonymns'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='synonymns',
        ),
        migrations.AddField(
            model_name='word',
            name='synonyms',
            field=models.ManyToManyField(blank=True, related_name='related_synonyms', to='web.word'),
        ),
    ]
